apiVersion: v1
kind: Service
metadata:
  name: syshub-service
spec:
  selector:
    app: syshub
    harness.io/color: blue   # This will be swapped to green on switch
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
