apiVersion: v1
kind: Service
metadata:
  name: syshub-service
spec:
  selector:
    app: syshub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Optional: You can let Kubernetes assign if you omit this
  type: NodePort
