pipeline:
  name: CI_SysHub
  identifier: CI_SM
  projectIdentifier: Harness_Dev1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: CI
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
            paths:
              - /root/.m2
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube_local
              namespace: harness-ci
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone
                  identifier: GitClone
                  spec:
                    connectorRef: github_connctor
                    repoName: SYSHub
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: FilePathCheck
                  identifier: checkFiles
                  spec:
                    connectorRef: dockerhub
                    image: ubuntu:22.04
                    shell: Bash
                    command: |-
                      apt update && apt install tree
                      tree
                      ls -la
                      ls -la SYSHub
                      pwd
                contextType: Pipeline
              - step:
                  type: Sonarqube
                  name: SonarqubeScan
                  identifier: SonarqubeScan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: debug
                    auth:
                      access_token: 7d2113669629d4ef75c18a7f70010e1d8e8588b8
                      domain: https://sonarcloud.io
                      ssl: true
                    tool:
                      project_key: Syshub
              - parallel:
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: BuildAndPushDockerRegistry_1
                      identifier: BuildAndPushDockerRegistry_1
                      spec:
                        connectorRef: DockerHub_DJErrorAccount
                        repo: djerror327/syshub
                        tags:
                          - SYSHub-1.0.0
                        dockerfile: SYSHub/Dockerfile
                        context: .
                  - step:
                      type: ArtifactoryUpload
                      name: ArtifactoryUpload
                      identifier: ArtifactoryUpload
                      spec:
                        connectorRef: antifactory
                        target: harness_ci-libs-snapshot/com/dj/SYSHub/1.0.0-SNAPSHOT/SYSHub-1.0.0-SNAPSHOT.jar
                        sourcePath: SYSHub/deploy/SYSHub/SYSHub-1.0.0-SNAPSHOT.jar
          buildIntelligence:
            enabled: false
