pipeline:
  name: CI_SysHub
  identifier: CI_SM
  projectIdentifier: Harness_Dev1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
            paths: []
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube_local
              namespace: harness-ci
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone
                  identifier: GitClone
                  spec:
                    connectorRef: github_connctor
                    repoName: SYSHub
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: build_code
                  identifier: build_code
                  spec:
                    connectorRef: dockerhub
                    image: maven:3.8.5-openjdk-17
                    shell: Sh
                    command: |-
                      mvn clean install
                      tree deploy
          buildIntelligence:
            enabled: false
