pipeline:
  name: Syshub
  identifier: Syshub
  projectIdentifier: Harness_Dev1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_connctor
        repoName: SYSHub
        build: <+input>
  stages:
    - stage:
        name: CI
        identifier: CI
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: minikube_local
              namespace: "harness-ci "
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: dummy
                  identifier: dummy
                  spec:
                    connectorRef: dockerhub
                    image: ubuntu:22.04
                    shell: Bash
                    command: ls -l
                  description: CI dummy
    - stage:
        name: Approval for CD
        identifier: Approval_for_CD
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approval for cd
                  identifier: approval_for_cd
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
    - stage:
        name: minikube_rolling
        identifier: minikube_deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: cd_minikube
            gitBranch: main
          environment:
            environmentRef: minikube_local
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: minikube_local_infa
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
