pipeline:
  name: Syshub
  identifier: Syshub
  projectIdentifier: Harness_Dev1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: minikube_bluegreen
        identifier: minikube_bluegreen
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: cd_minikube
          environment:
            environmentRef: minikube_local
            deployToAll: false
            infrastructureDefinitions:
              - identifier: minikube_local_infa
          execution:
            steps:
              - step:
                  name: Deploy Green
                  identifier: deployGreen
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    manifests:
                      - manifest:
                          identifier: greenDeploymentManifest
                          type: KubernetesManifest
                          spec:
                            store:
                              type: Git
                              spec:
                                connectorRef: github_connector
                                gitFetchType: Branch
                                branch: main
                                paths:
                                  - k8s/green/syshub-green.yaml
                      - manifest:
                          identifier: serviceManifest
                          type: KubernetesManifest
                          spec:
                            store:
                              type: Git
                              spec:
                                connectorRef: github_connector
                                gitFetchType: Branch
                                branch: main
                                paths:
                                  - k8s/green/service.yml
              - step:
                  type: HarnessApproval
                  name: Validate Green
                  identifier: validateGreen
                  timeout: 1d
                  spec:
                    approvalMessage: Please validate the green deployment
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
              - step:
                  name: Swap Services
                  identifier: swapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
              - step:
                  type: HarnessApproval
                  name: Approve Delete Blue
                  identifier: approveDeleteBlue
                  timeout: 1d
                  spec:
                    approvalMessage: Approve deletion of old blue deployment
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
              - step:
                  name: Delete Blue Deployment
                  identifier: deleteBlueDeployment
                  type: K8sDelete
                  timeout: 10m
                  spec:
                    deleteResources:
                      type: ResourceName
                      spec:
                        resourceNames:
                          - deployment syshub-blue
            rollbackSteps:
              - step:
                  name: Rollback Swap
                  identifier: rollbackSwap
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
