pipeline:
  name: Syshub
  identifier: Syshub
  projectIdentifier: Harness_Dev1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: minikube_bluegreen
        identifier: minikube_bluegreen
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: cd_minikube
          environment:
            environmentRef: minikube_local
            deployToAll: false
            infrastructureDefinitions:
              - identifier: minikube_local_infa
          execution:
            steps:
              - step:
                  name: Stage Deployment
                  identifier: stageDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    manifests:
                      - manifest:
                          identifier: blueDeploymentManifest
                          type: KubernetesManifest
                          spec:
                            store:
                              type: Git
                              spec:
                                connectorRef: github_connector
                                gitFetchType: Branch
                                paths:
                                  - manifests/syshub-blue.yaml
                                branch: main
                      - manifest:
                          identifier: serviceManifest
                          type: KubernetesManifest
                          spec:
                            store:
                              type: Git
                              spec:
                                connectorRef: github_connector
                                gitFetchType: Branch
                                paths:
                                  - manifests/syshub-service.yaml
                                branch: main
              - step:
                  type: HarnessApproval
                  name: BlueValidation
                  identifier: BlueValidation
                  spec:
                    approvalMessage: Please review the following information and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  name: Deploy Green
                  identifier: greenDeployment
                  type: K8sBlueGreenDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                    manifests:
                      - manifest:
                          identifier: greenDeploymentManifest
                          type: KubernetesManifest
                          spec:
                            store:
                              type: Git
                              spec:
                                connectorRef: github_connector
                                gitFetchType: Branch
                                paths:
                                  - manifests/syshub-green.yaml
                                branch: main
                      - manifest:
                          identifier: serviceManifest
                          type: KubernetesManifest
                          spec:
                            store:
                              type: Git
                              spec:
                                connectorRef: github_connector
                                gitFetchType: Branch
                                paths:
                                  - manifests/syshub-service.yaml
                                branch: main
              - step:
                  name: Swap primary with stage service
                  identifier: bgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
              - step:
                  type: HarnessApproval
                  name: Delete Old Deployment Approval
                  identifier: delete_red
                  spec:
                    approvalMessage: Please approve deletion of old deployment
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - step:
                  type: K8sDelete
                  name: Delete Old Deployment
                  identifier: K8sDelete_1
                  spec:
                    deleteResources:
                      type: ResourceName
                      spec:
                        resourceNames:
                          - deployment syshub-blue
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Swap primary with stage service
                  identifier: rollbackBgSwapServices
                  type: K8sBGSwapServices
                  timeout: 10m
                  spec:
                    skipDryRun: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
